/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Exercicio_Model;
import java.util.ArrayList;

/**
 *
 * @author 180000B1Z
 */
public class Tela_principal_Lixo extends javax.swing.JFrame {

    /**
     * Creates new form Tela_principal_Lixo
     */
    public Tela_principal_Lixo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_principal_Lixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_principal_Lixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_principal_Lixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_principal_Lixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<Exercicio_Model> lista_geral = new ArrayList<Exercicio_Model>();
                ArrayList<Exercicio_Model> lista_grupo = new ArrayList<Exercicio_Model>();

//anterior perna
                Exercicio_Model Agachamento_Livre = new Exercicio_Model("Agachamento Livre", "Anterior Perna", false, true);
                Agachamento_Livre.AddLista(lista_geral);
                Exercicio_Model Cadeira_Extensora = new Exercicio_Model("Cadeira extensora", "Anterior Perna", true, false);
                Cadeira_Extensora.AddLista(lista_geral);
                Exercicio_Model Leg_Press = new Exercicio_Model("Leg Press", "Anterior Perna", true, true);
                Leg_Press.AddLista(lista_geral);
                Exercicio_Model Hack_Machine = new Exercicio_Model("Hack Machine", "Anterior Perna", true, false);
                Hack_Machine.AddLista(lista_geral);
                Exercicio_Model Passada = new Exercicio_Model("Passada", "Anterior Perna", false, true);
                Passada.AddLista(lista_geral);
//posterior perna
                Exercicio_Model Stiff = new Exercicio_Model("Stiff", "Posterior Perna", false, true);
                Stiff.AddLista(lista_geral);
                Exercicio_Model Cadeira_Flexora = new Exercicio_Model("Cadeira extensora", "Posterior Perna", true, false);
                Cadeira_Flexora.AddLista(lista_geral);
                Exercicio_Model Afundo = new Exercicio_Model("Afundo", "Posterior Perna", false, true);
                Afundo.AddLista(lista_geral);
                Exercicio_Model Mesa_flexora = new Exercicio_Model("Mesa flexora", "Posterior Perna", true, false);
                Mesa_flexora.AddLista(lista_geral);
                Exercicio_Model Levantamento_Terra = new Exercicio_Model("Levantamento terra", "Posterior Perna", false, true);
                Levantamento_Terra.AddLista(lista_geral);
//peito
                Exercicio_Model Supino_Reto = new Exercicio_Model("Supino reto", "Peito", false, true);
                Supino_Reto.AddLista(lista_geral);
                Exercicio_Model Flexão_Bracos = new Exercicio_Model("Flexão de braços", "Peito", false, false);
                Flexão_Bracos.AddLista(lista_geral);
                Exercicio_Model Supino_Inclinado = new Exercicio_Model("Supino Inclinado", "Peito", false, true);
                Supino_Inclinado.AddLista(lista_geral);
                Exercicio_Model Supino_Declinado = new Exercicio_Model("Supino Declinado", "Peito", false, false);
                Supino_Declinado.AddLista(lista_geral);
                Exercicio_Model Cross_Over = new Exercicio_Model("Cross Over", "Peito", false, true);
                Cross_Over.AddLista(lista_geral);
                lista_grupo = Exercicio_Model.retornaListaExercicios_PorGrupo(lista_geral, "Peito");
                //costas

                //biceps
                //triceps
                //ombro
                new Tela_principal_Lixo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
